"""added added_by field

Revision ID: 713130f6810d
Revises: 
Create Date: 2023-06-22 15:35:06.059266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713130f6810d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opinion', sa.Column('added_by', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opinion', 'added_by')
    # ### end Alembic commands ###
